import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <main>
               <Header />
               <div className="flex-1">
                  <div className="max-w-4xl mx-auto p-6">{children}</div>
               </div>
               <Footer />
            </main>
         </body>
      </html>
   )
}
